services:
  web:
    build: .
    restart: always
    expose:
      - ${PORT}
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bepph.rule=Host(`bepph.hawari.dev`)"
      - "traefik.http.routers.bepph.entrypoints=web"
      - "traefik.http.services.bepph.loadbalancer.server.port=${PORT}"
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:${PORT}/api/heartbeat"]
      start_period: 60s
      interval: 3600s
      timeout: 5s
      retries: 5
    volumes:
      - "prisma:/app/prisma"
    networks:
      - traefik-network

volumes:
  prisma:

networks:
  traefik-network:
    external: true
